const env = import.meta.env;

export const PRODUCTION = env.VITE_APP_PRODUCTION === 'true';
export const API_URL = env.VITE_APP_API_URL;
export const GOOGLE_OAUTH_CLIENT_ID = env.VITE_APP_GOOGLE_OAUTH_CLIENT_ID;
export const FIREBASE_API_KEY = env.VITE_APP_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = env.VITE_APP_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = env.VITE_APP_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = env.VITE_APP_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID =
  env.VITE_APP_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = env.VITE_APP_FIREBASE_APP_ID;
export const FIREBASE_MEASUREMENT_ID = env.VITE_APP_FIREBASE_MEASUREMENT_ID;
export const FIREBASE_PROPERTY_ID = env.VITE_APP_FIREBASE_PROPERTY_ID;
